- name: Launch S3
  cloudformation:
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   stack_name: "apb-s3-{{ stack_identifier }}"
   state: "present"
   region: "{{ region }}"
   disable_rollback: false
   template: "{{ role_path }}/files/S3Bucket.yml"
   template_parameters:
     ApplicationName: "{{ ApplicationName }}"
     BucketName: "{{ BucketName }}"
     LoggingPrefix: "{{ LoggingPrefix }}"
     EnableGlacierLifeCycle: "{{ EnableGlacierLifeCycle }}"
     GlacierLifeCycleTransitionInDays: "{{ GlacierLifeCycleTransitionInDays }}"
     EnableVersioning: "{{ EnableVersioning }}"
     LifeCyclePrefix: "{{ LifeCyclePrefix }}"
     BucketAccessControl: "{{ BucketAccessControl }}"
   tags:
     Stack: "ansible-cloudformation"
     Application: "ansible-S3"
     Description: "{{ ansible_user_id }} S3 {{ ApplicationName }}"
  register: s3

- name: Check for CloudFormation error logs
  debug:
    var: s3.log

- name: Encode bind credentials
  asb_encode_binding:
    fields:
      bucket_arn: "{{ s3.stack_outputs.BucketArn }}"
      bucket_name: "{{ s3.stack_outputs.BucketName }}"
  when: s3.log | length < 1
